version: "3"

services:
  teamcity-server:
    image: jetbrains/teamcity-server:2020.2.2
    container_name: teamcity-server
    user: ${SYSTEM_UID}
    environment:
      TEAMCITY_LOGS: /opt/teamcity/logs
      TEAMCITY_DIST: /opt/teamcity
      TEAMCITY_DATA_PATH: /data/teamcity
    depends_on:
      - teamcity-postgres
    ports:
      - "${SERVER_PORT}:8111"
    volumes:
      - ./server/data:/data/teamcity:rw
    restart: "always"

  teamcity-agent-01:
    image: local-teamcity-agent
    build:
      context: ./docker
      dockerfile: ./Dockerfile.agent
      args:
        - USER_ID=${SYSTEM_UID}
        - DOCKER_GROUP_ID=${SYSTEM_DID}
        - AWS_KEY=${AWS_ACCESS_KEY_ID}
        - AWS_SECRET=${AWS_SECRET_ACCESS_KEY}
        - GIT_USER=${GIT_USER}
        - GIT_EMAIL=${GIT_EMAIL}
    depends_on:
      - teamcity-server
    container_name: teamcity-agent-01
    environment:
      SERVER_URL: "${SERVER_URL}"
      AGENT_NAME: "agent-01"
      AWS_DEFAULT_REGION: "${AWS_REGION}"
      RUN_AS_BUILDAGENT: "true"
    privileged: true
    volumes:
      - ./agents:/opt/teamcity:rw

  teamcity-postgres:
    image: postgres
    container_name: teamcity-postgres
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - ./db-data:/var/lib/postgresql/data
