version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.3-amd64
    container_name: dev-es8
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - xpack.security.enabled=false
      - http.cors.enabled=true
      - http.cors.allow-credentials=true
      - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
      - http.cors.allow-origin=/https?:\/\/localhost(:[0-9]+)?/
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./es-data:/usr/share/elasticsearch/data
      - ./es-log:/usr/share/elasticsearch/logs
    #command: bash -c "
    #    /usr/share/elasticsearch/bin/elasticsearch-plugin install analysis-smartcn
    #  "
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - esnet
    restart: always

  kibana:
    image: docker.elastic.co/kibana/kibana:8.1.3
    container_name: dev-kibana8
    environment:
      - "SERVER_NAME=kibana"
      - "ELASTICSEARCH_HOSTS=http://elasticsearch:9200"
    ports:
      - 5601:5601
    networks:
      - esnet
    restart: "unless-stopped"

volumes:
  es-data:
    driver: local

networks:
  esnet:
