version: '3.3'
services:
  postgres:
    image: postgres
    container_name: airflow-postgres
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
  scheduler:
    image: apache/airflow
    container_name: airflow-scheduler
    command: scheduler
    restart: unless-stopped
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
  webserver:
    image: apache/airflow
    container_name: airflow-server
    entrypoint: ./scripts/entrypoint.sh
    restart: unless-stopped
    depends_on:
      - postgres
      - scheduler
    env_file:
      - .env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./scripts:/opt/airflow/scripts
    ports:
      - "8082:8080"
