version:  '3'
services:
  pgadmin4:
      image: dpage/pgadmin4
      volumes:
        - ./servers.json:/pgadmin4/servers.json
      ports:
        - 5050:80
      container_name: pgadmin4
      environment:
        - PGADMIN_DEFAULT_EMAIL=me@mymain.com
        - PGADMIN_DEFAULT_PASSWORD=123
